IF NOT EXISTS(
    SELECT 1
    FROM sys.schemas
    WHERE name='silver'
)
BEGIN
    EXEC('CREATE SCHEMA silver ');
END;

CREATE TABLE silver.ingreso(
    ID_INGRESO INT IDENTITY(1,1) PRIMARY KEY,
    ANO_DOC SMALLINT NOT NULL,
    MES_DOC TINYINT NOT NULL,
    UBIGEO VARCHAR(6) NOT NULL,
    DEPARTAMENTO_EJECUTORA_NOMBRE VARCHAR(50) NULL,
    PROVINCIA_EJECUTORA_NOMBRE VARCHAR(50) NULL,
    DISTRITO_EJECUTORA_NOMBRE VARCHAR(50) NULL,
    NIVEL_GOBIERNO_NOMBRE VARCHAR(30) NULL,
    RUBRO_NOMBRE VARCHAR(100) NULL,
    MONTO_PIA DECIMAL(18,2) NOT NULL,
    MONTO_PIM DECIMAL(18,2) NOT NULL,
    MONTO_RECAUDADO DECIMAL(18,2) NOT NULL
);

CREATE INDEX IX_ingreso_ubigeo_ano ON silver.ingreso (UBIGEO, ANO_DOC);

CREATE TABLE silver.meta_predial(
    ANO_ESTADISTICA SMALLINT NOT NULL,
    SEC_EJEC VARCHAR(6) NOT NULL,
    UBIGEO VARCHAR(6) NOT NULL,
    DEPARTAMENTO_NOMBRE VARCHAR(50) NULL,
    PROVINCIA_NOMBRE VARCHAR(50) NULL,
    DISTRITO_NOMBRE VARCHAR(50) NULL,
    MUNICIPALIDAD_NOMBRE VARCHAR(120) NULL,
    MON_EMISIONPREDIAL_AFECTO DECIMAL(18,2) NULL,
    MON_EMISIONPREDIAL_EXON DECIMAL(18,2) NULL,
    MON_BASEIMPONIBLE_AFECTO DECIMAL(18,2) NULL,
    MON_RECAUDACTUAL_ORDIN DECIMAL(18,2) NULL,
    MON_RECAUDACTUAL_COAC DECIMAL(18,2) NULL,
    MON_RECAUDANTER_ORDI DECIMAL(18,2) NULL,
    MON_RECAUDANTER_COAC DECIMAL(18,2) NULL,
    MON_SALDOPREDIAL_ORD DECIMAL(18,2) NULL,
    MON_SALDOPREDIAL_COAC DECIMAL(18,2) NULL,
    CUMPLIMIENTO_META_PREDIAL FLOAT NULL,
    FLAG_CUMPLIMIENTO_ATIPICO BIT NOT NULL,
    FLAG_EMISION_SOSPECHOSA BIT NOT NULL,
    CLASIFICACION VARCHAR(1) NULL,
    TIPO_META SMALLINT NULL,
    ANO_CLASIFICACION SMALLINT NULL,
    CONSTRAINT PK_meta_predial PRIMARY KEY (SEC_EJEC, ANO_ESTADISTICA)
);

-- Las 90 columnas P23_* (instrumentos de gestion de renamu) no se listan
-- a mano aca: cargar_silver.py reemplaza el marcador de columnas P23
-- (mas abajo, dentro del CREATE TABLE) en tiempo de ejecucion, leyendo
-- los nombres reales del Parquet de renamu (mismo criterio que
-- Src/silver/construir_renamu.py: prefijo "P23_"), para que la tabla
-- nunca se desincronice del dato real y para no tipear 90 lineas casi
-- identicas a mano.
CREATE TABLE silver.renamu(
    ANO SMALLINT NOT NULL,
    UBIGEO VARCHAR(6) NOT NULL,
    DEPARTAMENTO VARCHAR(30) NULL,
    PROVINCIA VARCHAR(50) NULL,
    DISTRITO VARCHAR(60) NULL,
    TIPOMUNI VARCHAR(2) NULL,
    P19D_T INT NULL,
    P19D_NM INT NULL,
    P19D_NH INT NULL,
    P19D_CM INT NULL,
    P19D_CH INT NULL,
    P19D_LM INT NULL,
    P19D_LH INT NULL,
    P19D_VM INT NULL,
    P19D_VH INT NULL,
    P19_1_T INT NULL,
    P19_2_T INT NULL,
    P19_3_T INT NULL,
    P19_4_T INT NULL,
    P19_5_T INT NULL,
    P19_6_T INT NULL,
    {{COLUMNAS_P23}}
    P32 VARCHAR(2) NULL,
    P32_1_T INT NULL,
    P32_1_M INT NULL,
    P32_1_H INT NULL,
    P17_8 VARCHAR(2) NULL,
    PCT_PERSONAL_NOMBRADO FLOAT NULL, 
    CONSTRAINT PK_renamu PRIMARY KEY (UBIGEO, ANO)
);