use GoldFiscal;
if not exists(
	select 1
	from sys.schemas
	where name='gold'
	)
begin
	exec('CREATE SCHEMA gold');
end;

IF OBJECT_ID('gold.UBICACION', 'U') IS NOT NULL DROP TABLE gold.UBICACION;
CREATE TABLE gold.UBICACION(
	PREFIJO_UBIGEO VARCHAR(4) NOT NULL PRIMARY KEY,
	NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
	NOMBRE_PROVINCIA VARCHAR(50) NOT NULL,
	MACRO_REGION VARCHAR(20) NOT NULL);

IF OBJECT_ID('gold.RUBRO', 'U') IS NOT NULL DROP TABLE gold.RUBRO;
CREATE TABLE gold.RUBRO (
    RUBRO_NOMBRE            VARCHAR(100) NOT NULL PRIMARY KEY,
    CATEGORIA               VARCHAR(30)  NOT NULL,
    ES_NUMERADOR_AUTONOMIA  BIT          NOT NULL,
    ENTRA_EN_DENOMINADOR    BIT          NOT NULL
);


INSERT INTO gold.RUBRO (RUBRO_NOMBRE,CATEGORIA,ES_NUMERADOR_AUTONOMIA,ENTRA_EN_DENOMINADOR) VALUES
('FONDO DE COMPENSACION REGIONAL - FONCOR','TRANSFERENCIA',0,1),
('RECURSOS DIRECTAMENTE RECAUDADOS','RECURSOS_PROPIOS',1,1),
('DONACIONES Y TRANSFERENCIAS','TRANSFERENCIA',0,1),
('CANON Y SOBRECANON, REGALIAS, RENTA DE ADUANAS Y PARTICIPACIONES','CANON',0,1),
('FONDO DE COMPENSACION MUNICIPAL','TRANSFERENCIA',0,1),
('IMPUESTOS MUNICIPALES','RECURSOS_PROPIOS',1,1),
('RECURSOS POR OPERACIONES OFICIALES DE CREDITO','DEUDA',0,0);
INSERT INTO gold.UBICACION (PREFIJO_UBIGEO, NOMBRE_DEPARTAMENTO, NOMBRE_PROVINCIA, MACRO_REGION)
SELECT DISTINCT
    LEFT(UBIGEO, 4),
    DEPARTAMENTO_EJECUTORA_NOMBRE,
    PROVINCIA_EJECUTORA_NOMBRE,
    'PENDIENTE'
FROM silver.ingreso;

UPDATE gold.UBICACION
SET MACRO_REGION =
    CASE
        WHEN PREFIJO_UBIGEO = '1501' THEN 'Lima Metropolitana'
        WHEN PREFIJO_UBIGEO = '0701' THEN 'Lima Metropolitana'
        WHEN LEFT(PREFIJO_UBIGEO, 2) = '15' THEN 'Lima Provincias'
        WHEN LEFT(PREFIJO_UBIGEO, 2) IN ('24','20','14','13','06','02') THEN 'Norte'
        WHEN LEFT(PREFIJO_UBIGEO, 2) IN ('11','10','19','12','09')      THEN 'Centro'
        WHEN LEFT(PREFIJO_UBIGEO, 2) IN ('04','05','03','08','21','18','23') THEN 'Sur'
        WHEN LEFT(PREFIJO_UBIGEO, 2) IN ('16','22','01','25','17')      THEN 'Oriente'
    END;
