IF OBJECT_ID('gold.AUTONOMIA_FISCAL', 'U') IS NOT NULL DROP TABLE gold.AUTONOMIA_FISCAL;
CREATE TABLE gold.AUTONOMIA_FISCAL (
    UBIGEO                  VARCHAR(6)    NOT NULL,
    ANO                      SMALLINT      NOT NULL,
    PREFIJO_UBIGEO           VARCHAR(4)    NOT NULL,
    MONTO_RECURSOS_PROPIOS   DECIMAL(18,2) NOT NULL,
    MONTO_TRANSFERENCIAS     DECIMAL(18,2) NOT NULL,
    MONTO_CANON              DECIMAL(18,2) NOT NULL,
    MONTO_DEUDA              DECIMAL(18,2) NOT NULL,
    MONTO_TOTAL_SIN_DEUDA    DECIMAL(18,2) NOT NULL,
    RATIO_AUTONOMIA          FLOAT         NULL,
    FLAG_DENOMINADOR_NEGATIVO BIT          NOT NULL,
    CONSTRAINT PK_autonomia_fiscal PRIMARY KEY (UBIGEO, ANO)
);

CREATE OR ALTER PROCEDURE gold.sp_cargar_autonomia_fiscal
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE gold.AUTONOMIA_FISCAL;

    WITH AGREGADO AS (
        SELECT
            i.UBIGEO,
            i.ANO_DOC AS ANO,
            LEFT(i.UBIGEO, 4) AS PREFIJO_UBIGEO,
            SUM(CASE WHEN r.ES_NUMERADOR_AUTONOMIA = 1 THEN i.MONTO_RECAUDADO ELSE 0 END) AS MONTO_RECURSOS_PROPIOS,
            SUM(CASE WHEN r.CATEGORIA = 'TRANSFERENCIA' THEN i.MONTO_RECAUDADO ELSE 0 END) AS MONTO_TRANSFERENCIAS,
            SUM(CASE WHEN r.CATEGORIA = 'CANON' THEN i.MONTO_RECAUDADO ELSE 0 END) AS MONTO_CANON,
            SUM(CASE WHEN r.CATEGORIA = 'DEUDA' THEN i.MONTO_RECAUDADO ELSE 0 END) AS MONTO_DEUDA,
            SUM(CASE WHEN r.ENTRA_EN_DENOMINADOR = 1 THEN i.MONTO_RECAUDADO ELSE 0 END) AS MONTO_TOTAL_SIN_DEUDA
        FROM silver.ingreso i
        JOIN gold.RUBRO r ON r.RUBRO_NOMBRE = i.RUBRO_NOMBRE
        WHERE i.NIVEL_GOBIERNO_NOMBRE = 'GOBIERNOS LOCALES'
        GROUP BY i.UBIGEO, i.ANO_DOC, LEFT(i.UBIGEO, 4)
    )
    INSERT INTO gold.AUTONOMIA_FISCAL (
        UBIGEO, ANO, PREFIJO_UBIGEO,
        MONTO_RECURSOS_PROPIOS, MONTO_TRANSFERENCIAS, MONTO_CANON, MONTO_DEUDA,
        MONTO_TOTAL_SIN_DEUDA, RATIO_AUTONOMIA, FLAG_DENOMINADOR_NEGATIVO
    )
    SELECT
        UBIGEO, ANO, PREFIJO_UBIGEO,
        MONTO_RECURSOS_PROPIOS, MONTO_TRANSFERENCIAS, MONTO_CANON, MONTO_DEUDA,
        MONTO_TOTAL_SIN_DEUDA,
        CAST(MONTO_RECURSOS_PROPIOS AS FLOAT) / NULLIF(MONTO_TOTAL_SIN_DEUDA, 0) AS RATIO_AUTONOMIA,
        CASE WHEN MONTO_TOTAL_SIN_DEUDA < 0 THEN 1 ELSE 0 END AS FLAG_DENOMINADOR_NEGATIVO
    FROM AGREGADO;

    PRINT 'Filas insertadas: ' + CAST(@@ROWCOUNT AS VARCHAR);
END;
