IF OBJECT_ID('gold.REPARTO_TERRITORIAL', 'U') IS NOT NULL DROP TABLE gold.REPARTO_TERRITORIAL;
CREATE TABLE gold.REPARTO_TERRITORIAL (
    MACRO_REGION            VARCHAR(30)   NOT NULL,
    NOMBRE_DEPARTAMENTO     VARCHAR(50)   NOT NULL,
    NIVEL_GOBIERNO_NOMBRE   VARCHAR(30)   NOT NULL,
    ANO                     SMALLINT      NOT NULL,
    MONTO_PIA               DECIMAL(18,2) NOT NULL,
    MONTO_PIM               DECIMAL(18,2) NOT NULL,
    MONTO_RECAUDADO         DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_reparto_territorial PRIMARY KEY (MACRO_REGION, NOMBRE_DEPARTAMENTO, NIVEL_GOBIERNO_NOMBRE, ANO)
);

CREATE OR ALTER PROCEDURE gold.sp_cargar_reparto_territorial
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE gold.REPARTO_TERRITORIAL;

    INSERT INTO gold.REPARTO_TERRITORIAL (
        MACRO_REGION, NOMBRE_DEPARTAMENTO, NIVEL_GOBIERNO_NOMBRE, ANO,
        MONTO_PIA, MONTO_PIM, MONTO_RECAUDADO
    )
    SELECT
        u.MACRO_REGION,
        u.NOMBRE_DEPARTAMENTO,
        i.NIVEL_GOBIERNO_NOMBRE,
        i.ANO_DOC AS ANO,
        SUM(i.MONTO_PIA) AS MONTO_PIA,
        SUM(i.MONTO_PIM) AS MONTO_PIM,
        SUM(i.MONTO_RECAUDADO) AS MONTO_RECAUDADO
    FROM silver.ingreso i
    JOIN gold.UBICACION u ON u.PREFIJO_UBIGEO = LEFT(i.UBIGEO, 4)
    GROUP BY u.MACRO_REGION, u.NOMBRE_DEPARTAMENTO, i.NIVEL_GOBIERNO_NOMBRE, i.ANO_DOC;

    PRINT 'Filas insertadas: ' + CAST(@@ROWCOUNT AS VARCHAR);
END;

EXEC gold.sp_cargar_reparto_territorial;
