IF OBJECT_ID('gold.REPARTO_NIVEL_GOBIERNO', 'U') IS NOT NULL DROP TABLE gold.REPARTO_NIVEL_GOBIERNO;
CREATE TABLE gold.REPARTO_NIVEL_GOBIERNO (
    NIVEL_GOBIERNO_NOMBRE VARCHAR(30)   NOT NULL,
    ANO                    SMALLINT      NOT NULL,
    MONTO_PIM              DECIMAL(18,2) NOT NULL,
    MONTO_RECAUDADO        DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_reparto_nivel_gobierno PRIMARY KEY (NIVEL_GOBIERNO_NOMBRE, ANO)
);
