IF OBJECT_ID('gold.CUMPLIMIENTO_PREDIAL', 'U') IS NOT NULL DROP TABLE gold.CUMPLIMIENTO_PREDIAL;
CREATE TABLE gold.CUMPLIMIENTO_PREDIAL (
    UBIGEO                      VARCHAR(6)    NOT NULL,
    ANO                          SMALLINT      NOT NULL,
    PREFIJO_UBIGEO               VARCHAR(4)    NOT NULL,
    CLASIFICACION                VARCHAR(1)    NULL,
    MON_EMISIONPREDIAL_AFECTO    DECIMAL(18,2) NOT NULL,
    MON_RECAUDACTUAL_ORDIN       DECIMAL(18,2) NOT NULL,
    MON_RECAUDACTUAL_COAC        DECIMAL(18,2) NOT NULL,
    MON_RECAUDACTUAL_TOTAL       DECIMAL(18,2) NOT NULL,
    BRECHA_EMISION_RECAUDACION   DECIMAL(18,2) NOT NULL,
    CUMPLIMIENTO_META_PREDIAL    FLOAT         NULL,
    FLAG_CUMPLIMIENTO_ATIPICO    BIT           NOT NULL,
    FLAG_EMISION_SOSPECHOSA      BIT           NOT NULL,
    CONSTRAINT PK_cumplimiento_predial PRIMARY KEY (UBIGEO, ANO)
);

CREATE OR ALTER PROCEDURE gold.sp_cargar_cumplimiento_predial
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE gold.CUMPLIMIENTO_PREDIAL;

    INSERT INTO gold.CUMPLIMIENTO_PREDIAL (
        UBIGEO, ANO, PREFIJO_UBIGEO, CLASIFICACION,
        MON_EMISIONPREDIAL_AFECTO, MON_RECAUDACTUAL_ORDIN, MON_RECAUDACTUAL_COAC,
        MON_RECAUDACTUAL_TOTAL, BRECHA_EMISION_RECAUDACION,
        CUMPLIMIENTO_META_PREDIAL, FLAG_CUMPLIMIENTO_ATIPICO, FLAG_EMISION_SOSPECHOSA
    )
    SELECT
        m.UBIGEO,
        m.ANO_ESTADISTICA AS ANO,
        LEFT(m.UBIGEO, 4) AS PREFIJO_UBIGEO,
        m.CLASIFICACION,
        m.MON_EMISIONPREDIAL_AFECTO,
        m.MON_RECAUDACTUAL_ORDIN,
        m.MON_RECAUDACTUAL_COAC,
        m.MON_RECAUDACTUAL_ORDIN + m.MON_RECAUDACTUAL_COAC AS MON_RECAUDACTUAL_TOTAL,
        m.MON_EMISIONPREDIAL_AFECTO - (m.MON_RECAUDACTUAL_ORDIN + m.MON_RECAUDACTUAL_COAC) AS BRECHA_EMISION_RECAUDACION,
        m.CUMPLIMIENTO_META_PREDIAL,
        m.FLAG_CUMPLIMIENTO_ATIPICO,
        m.FLAG_EMISION_SOSPECHOSA
    FROM silver.meta_predial m;

    PRINT 'Filas insertadas: ' + CAST(@@ROWCOUNT AS VARCHAR);

    -- Reporte, no filtro: PREFIJO_UBIGEO no depende de gold.UBICACION
    -- para cargarse (ver mas arriba), pero se avisa si algun dia deja
    -- de encontrar match, para no descubrirlo recien en Power BI.
    DECLARE @sin_dimension INT = (
        SELECT COUNT(*) FROM gold.CUMPLIMIENTO_PREDIAL c
        LEFT JOIN gold.UBICACION u ON u.PREFIJO_UBIGEO = c.PREFIJO_UBIGEO
        WHERE u.PREFIJO_UBIGEO IS NULL
    );
    PRINT 'Prefijos sin match en gold.UBICACION: ' + CAST(@sin_dimension AS VARCHAR);
END;

EXEC gold.sp_cargar_cumplimiento_predial;
